language: generic

matrix:
  include:
    - name: CUDA 10
      env:
        - CUDA=10.1.105-1
        - CUDA_SHORT=10.1
        - UBUNTU_VERSION=ubuntu1804
      dist: bionic

packages:
  - gcc-6
  - g++-6
  - cmake

before_install:

  - sudo apt install -y nvidia-cuda-dev nvidia-cuda-toolkit
  - sudo mkdir /usr/local/cuda
  - sudo cp -r /usr/bin/ /usr/local/cuda


  - sudo apt-get install libopencv-dev
  - sudo apt-get -y install libdevil-dev
  - sudo apt -y install libglew-dev
  - sudo apt-get install -y glew-utils
  - sudo apt-get -y install libglu1-mesa-dev freeglut3-dev mesa-common-dev
  - sudo apt install python3-opencv
  - sudo apt-get -y install cmake
  - sudo apt-get -y install libboost-all-dev

  - cd externals
  - cd ICPCUDA
  - git submodule update --init
  - cd third-party/Pangolin/
  - mkdir build
  - cd build
  - cmake ../ -DEIGEN_INCLUDE_DIR=build/leoneed03/GDR/externals/ICPCUDA/third-party/Eigen
  - make -j12
  - cd ../../../
  - mkdir build
  - cd build/
  - cmake ..
  - make -j12
  - cd
  - cd build/leoneed03/GDR


  - cd siftgpu
  - sudo make
  - cd ..
  - ls

  - cd externals/gtsam
  - sudo mkdir build
  - cd build
  - sudo cmake ..
  - sudo make install
  - cd ..
  - cd ..
  - cd ..

  - sudo apt-get -y install libstdc++6
  - sudo apt-get install g++
  - sudo apt install libpcl-dev
  - sudo apt-get -y install libeigen3-dev
  - sudo apt-get -y install libboost-dev
  - sudo apt-get -y install libboost-test-dev
  - sudo apt-get -y install libboost-system-dev
  - sudo apt-get -y install libboost-filesystem-dev
  - sudo apt-get -y install libboost-thread-dev
  - sudo apt-get -y install libboost-program-options-dev
  - sudo apt-get -y install libtbb-dev


script:
  - cd
  - cd build
  - ls
  - cd leoneed03
  - ls
  - cd GDR
  - ls
  - mkdir build
  - cd build
  - cmake ../
  - make
  #- ./testSIFTGPU